# Generated by Django 3.0.3 on 2020-02-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Priority')),
            ],
        ),
    ]
