# Generated by Django 3.0.3 on 2020-02-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_taskgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.TaskGroup'),
            preserve_default=False,
        ),
    ]
