# Generated by Django 3.0.3 on 2020-02-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200221_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_group',
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
