# Generated by Django 3.0.3 on 2020-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20200221_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
