# Generated by Django 3.0.3 on 2020-02-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_taskgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskgroup',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.TaskGroup'),
            preserve_default=False,
        ),
    ]
