# Generated by Django 3.0.3 on 2020-02-21 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0013_auto_20200221_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='TaskGroupOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
