# Generated by Django 3.0.3 on 2020-02-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_taskgroup_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='owner',
        ),
    ]
