# Generated by Django 3.0.3 on 2020-02-21 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0016_taskgroup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='accepted',
            field=models.ManyToManyField(related_name='TaskGroupAccepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
